

export const symptomsText = `muscle_wasting	
high_fever	
extra_marital_contacts	
patches_in_throat	
extra_marital_contacts	
muscle_wasting	
patches_in_throat	
high_fever	
extra_marital_contacts	
muscle_wasting	
patches_in_throat	
high_fever	
extra_marital_contacts	
muscle_wasting	
patches_in_throat	
high_fever	
patches_in_throat	
high_fever	
extra_marital_contacts	
pus_filled_pimples	
blackheads	
scurring	
skin_rash	
blackheads	
scurring	
skin_rash	
pus_filled_pimples	
blackheads	
scurring	
skin_rash	
pus_filled_pimples	
blackheads	
skin_rash	
pus_filled_pimples	
scurring	
vomiting	
abdominal_pain	
swelling_of_stomach	
distention_of_abdomen	
history_of_alcohol_consumption	
fluid_overload	
vomiting	
yellowish_skin	
abdominal_pain	
distention_of_abdomen	
history_of_alcohol_consumption	
fluid_overload	
vomiting	
yellowish_skin	
abdominal_pain	
swelling_of_stomach	
distention_of_abdomen	
fluid_overload	
vomiting	
yellowish_skin	
abdominal_pain	
swelling_of_stomach	
distention_of_abdomen	
history_of_alcohol_consumption	
fluid_overload	
vomiting	
yellowish_skin	
abdominal_pain	
swelling_of_stomach	
distention_of_abdomen	
history_of_alcohol_consumption	
vomiting	
yellowish_skin	
swelling_of_stomach	
distention_of_abdomen	
history_of_alcohol_consumption	
fluid_overload	
yellowish_skin	
abdominal_pain	
swelling_of_stomach	
distention_of_abdomen	
history_of_alcohol_consumption	
fluid_overload	
continuous_sneezing	
chills	
watering_from_eyes	
continuous_sneezing	
shivering	
chills	
watering_from_eyes	
continuous_sneezing	
shivering	
chills	
continuous_sneezing	
shivering	
watering_from_eyes	
shivering	
chills	
watering_from_eyes	
muscle_weakness	
stiff_neck	
movement_stiffness	
painful_walking	
muscle_weakness	
stiff_neck	
swelling_joints	
movement_stiffness	
painful_walking	
muscle_weakness	
stiff_neck	
swelling_joints	
movement_stiffness	
muscle_weakness	
stiff_neck	
swelling_joints	
painful_walking	
muscle_weakness	
swelling_joints	
movement_stiffness	
painful_walking	
stiff_neck	
swelling_joints	
movement_stiffness	
painful_walking	
cough	
high_fever	
breathlessness	
family_history	
mucoid_sputum	
fatigue	
cough	
breathlessness	
family_history	
mucoid_sputum	
fatigue	
cough	
high_fever	
breathlessness	
family_history	
mucoid_sputum	
fatigue	
cough	
high_fever	
breathlessness	
family_history	
mucoid_sputum	
fatigue	
cough	
high_fever	
breathlessness	
mucoid_sputum	
fatigue	
cough	
high_fever	
family_history	
mucoid_sputum	
fatigue	
cough	
high_fever	
breathlessness	
family_history	
fatigue	
cough	
high_fever	
breathlessness	
mucoid_sputum	
back_pain	
neck_pain	
dizziness	
loss_of_balance	
back_pain	
weakness_in_limbs	
dizziness	
loss_of_balance	
back_pain	
weakness_in_limbs	
neck_pain	
dizziness	
loss_of_balance	
back_pain	
weakness_in_limbs	
neck_pain	
dizziness	
back_pain	
weakness_in_limbs	
neck_pain	
loss_of_balance	
back_pain	
weakness_in_limbs	
neck_pain	
loss_of_balance	
weakness_in_limbs	
neck_pain	
dizziness	
loss_of_balance	
skin_rash	
fatigue	
lethargy	
high_fever	
headache	
loss_of_appetite	
mild_fever	
swelled_lymph_nodes	
malaise	
red_spots_over_body	
itching	
fatigue	
lethargy	
high_fever	
headache	
loss_of_appetite	
mild_fever	
swelled_lymph_nodes	
malaise	
red_spots_over_body	
itching	
skin_rash	
fatigue	
high_fever	
headache	
loss_of_appetite	
mild_fever	
swelled_lymph_nodes	
malaise	
red_spots_over_body	
itching	
skin_rash	
fatigue	
lethargy	
headache	
loss_of_appetite	
mild_fever	
swelled_lymph_nodes	
malaise	
red_spots_over_body	
itching	
skin_rash	
fatigue	
lethargy	
high_fever	
headache	
loss_of_appetite	
mild_fever	
malaise	
red_spots_over_body	
itching	
skin_rash	
fatigue	
lethargy	
high_fever	
headache	
loss_of_appetite	
mild_fever	
swelled_lymph_nodes	
malaise	
red_spots_over_body	
itching	
skin_rash	
fatigue	
lethargy	
high_fever	
headache	
loss_of_appetite	
mild_fever	
swelled_lymph_nodes	
malaise	
red_spots_over_body	
itching	
skin_rash	
fatigue	
lethargy	
high_fever	
headache	
loss_of_appetite	
mild_fever	
malaise	
red_spots_over_body	
itching	
skin_rash	
fatigue	
lethargy	
high_fever	
loss_of_appetite	
mild_fever	
swelled_lymph_nodes	
malaise	
red_spots_over_body	
itching	
skin_rash	
fatigue	
lethargy	
high_fever	
headache	
loss_of_appetite	
mild_fever	
swelled_lymph_nodes	
malaise	
red_spots_over_body	
itching	
skin_rash	
fatigue	
lethargy	
high_fever	
headache	
loss_of_appetite	
mild_fever	
swelled_lymph_nodes	
malaise	
red_spots_over_body	
itching	
skin_rash	
fatigue	
lethargy	
high_fever	
loss_of_appetite	
mild_fever	
swelled_lymph_nodes	
malaise	
red_spots_over_body	
itching	
skin_rash	
fatigue	
lethargy	
high_fever	
headache	
loss_of_appetite	
mild_fever	
swelled_lymph_nodes	
malaise	
red_spots_over_body	
itching	
skin_rash	
fatigue	
lethargy	
high_fever	
headache	
loss_of_appetite	
mild_fever	
swelled_lymph_nodes	
malaise	
red_spots_over_body	
itching	
skin_rash	
fatigue	
lethargy	
high_fever	
headache	
loss_of_appetite	
mild_fever	
swelled_lymph_nodes	
malaise	
red_spots_over_body	
itching	
skin_rash	
fatigue	
lethargy	
high_fever	
headache	
loss_of_appetite	
mild_fever	
swelled_lymph_nodes	
malaise	
red_spots_over_body	
itching	
skin_rash	
fatigue	
lethargy	
high_fever	
headache	
loss_of_appetite	
mild_fever	
swelled_lymph_nodes	
malaise	
red_spots_over_body	
itching	
skin_rash	
fatigue	
lethargy	
high_fever	
headache	
loss_of_appetite	
mild_fever	
swelled_lymph_nodes	
malaise	
red_spots_over_body	
itching	
skin_rash	
fatigue	
lethargy	
high_fever	
headache	
loss_of_appetite	
mild_fever	
swelled_lymph_nodes	
malaise	
red_spots_over_body	
itching	
skin_rash	
fatigue	
lethargy	
high_fever	
headache	
loss_of_appetite	
mild_fever	
swelled_lymph_nodes	
malaise	
red_spots_over_body	
itching	
skin_rash	
fatigue	
lethargy	
high_fever	
headache	
loss_of_appetite	
mild_fever	
swelled_lymph_nodes	
malaise	
red_spots_over_body	
itching	
skin_rash	
fatigue	
lethargy	
high_fever	
headache	
loss_of_appetite	
mild_fever	
swelled_lymph_nodes	
malaise	
red_spots_over_body	
itching	
skin_rash	
fatigue	
lethargy	
high_fever	
headache	
loss_of_appetite	
mild_fever	
swelled_lymph_nodes	
malaise	
red_spots_over_body	
itching	
skin_rash	
fatigue	
lethargy	
high_fever	
headache	
loss_of_appetite	
mild_fever	
swelled_lymph_nodes	
malaise	
red_spots_over_body	
itching	
skin_rash	
fatigue	
lethargy	
high_fever	
headache	
loss_of_appetite	
mild_fever	
swelled_lymph_nodes	
malaise	
red_spots_over_body	
itching	
skin_rash	
fatigue	
lethargy	
high_fever	
headache	
loss_of_appetite	
mild_fever	
swelled_lymph_nodes	
malaise	
red_spots_over_body	
itching	
skin_rash	
fatigue	
lethargy	
high_fever	
headache	
loss_of_appetite	
mild_fever	
swelled_lymph_nodes	
malaise	
red_spots_over_body	
itching	
skin_rash	
fatigue	
lethargy	
high_fever	
headache	
loss_of_appetite	
mild_fever	
swelled_lymph_nodes	
malaise	
red_spots_over_body	
itching	
skin_rash	
fatigue	
lethargy	
high_fever	
headache	
loss_of_appetite	
mild_fever	
swelled_lymph_nodes	
malaise	`;




export const medicalData = [
    { disease: "AIDS", symptoms: ["muscle_wasting", "high_fever", "extra_marital_contacts"] },
    { disease: "AIDS", symptoms: ["muscle_wasting", "patches_in_throat", "extra_marital_contacts"] },
    { disease: "AIDS", symptoms: ["muscle_wasting", "patches_in_throat", "high_fever", "extra_marital_contacts"] },
    { disease: "AIDS", symptoms: ["muscle_wasting", "patches_in_throat", "high_fever"] },
    { disease: "AIDS", symptoms: ["patches_in_throat", "high_fever", "extra_marital_contacts"] },
    { disease: "Acne", symptoms: ["pus_filled_pimples", "blackheads", "scurring"] },
    { disease: "Acne", symptoms: ["skin_rash", "blackheads", "scurring"] },
    { disease: "Acne", symptoms: ["skin_rash", "pus_filled_pimples", "blackheads", "scurring"] },
    { disease: "Acne", symptoms: ["skin_rash", "pus_filled_pimples", "blackheads"] },
    { disease: "Acne", symptoms: ["skin_rash", "pus_filled_pimples", "scurring", "high_fever"] },
    { disease: "Acne", symptoms: ["skin_rash", "pus_filled_pimples", "scurring"] },
    { disease: "Alcoholic hepatitis", symptoms: ["vomiting", "abdominal_pain", "swelling_of_stomach", "distention_of_abdomen", "history_of_alcohol_consumption", "fluid_overload"] },
    { disease: "Alcoholic hepatitis", symptoms: ["vomiting", "yellowish_skin", "abdominal_pain", "distention_of_abdomen", "history_of_alcohol_consumption", "fluid_overload"] },
    { disease: "Alcoholic hepatitis", symptoms: ["vomiting", "yellowish_skin", "abdominal_pain", "swelling_of_stomach", "distention_of_abdomen", "fluid_overload"] },
    { disease: "Alcoholic hepatitis", symptoms: ["vomiting", "yellowish_skin", "abdominal_pain", "swelling_of_stomach", "distention_of_abdomen", "history_of_alcohol_consumption", "fluid_overload"] },
    { disease: "Alcoholic hepatitis", symptoms: ["vomiting", "yellowish_skin", "abdominal_pain", "swelling_of_stomach", "distention_of_abdomen", "history_of_alcohol_consumption"] },
    { disease: "Alcoholic hepatitis", symptoms: ["vomiting", "yellowish_skin", "abdominal_pain", "swelling_of_stomach", "history_of_alcohol_consumption", "fluid_overload"] },
    { disease: "Alcoholic hepatitis", symptoms: ["vomiting", "yellowish_skin", "swelling_of_stomach", "distention_of_abdomen", "history_of_alcohol_consumption", "fluid_overload"] },
    { disease: "Alcoholic hepatitis", symptoms: ["yellowish_skin", "abdominal_pain", "swelling_of_stomach", "distention_of_abdomen", "history_of_alcohol_consumption", "fluid_overload"] },
    { disease: "Allergy", symptoms: ["continuous_sneezing", "chills", "watering_from_eyes"] },
    { disease: "Allergy", symptoms: ["continuous_sneezing", "shivering", "chills", "watering_from_eyes"] },
    { disease: "Allergy", symptoms: ["continuous_sneezing", "shivering", "chills"] },
    { disease: "Allergy", symptoms: ["continuous_sneezing", "shivering", "watering_from_eyes"] },
    { disease: "Allergy", symptoms: ["shivering", "chills", "watering_from_eyes"] }
];
