

export const symptomsText = `muscle_wasting	
high_fever	
extra_marital_contacts	
patches_in_throat	
extra_marital_contacts	
muscle_wasting	
patches_in_throat	
high_fever	
extra_marital_contacts	
muscle_wasting	
patches_in_throat	
high_fever	
extra_marital_contacts	
muscle_wasting	
patches_in_throat	
high_fever	
patches_in_throat	
high_fever	
extra_marital_contacts	
pus_filled_pimples	
blackheads	
scurring	
skin_rash	
blackheads	
scurring	
skin_rash	
pus_filled_pimples	
blackheads	
scurring	
skin_rash	
pus_filled_pimples	
blackheads	
skin_rash	
pus_filled_pimples	
scurring	
vomiting	
abdominal_pain	
swelling_of_stomach	
distention_of_abdomen	
history_of_alcohol_consumption	
fluid_overload	
vomiting	
yellowish_skin	
abdominal_pain	
distention_of_abdomen	
history_of_alcohol_consumption	
fluid_overload	
vomiting	
yellowish_skin	
abdominal_pain	
swelling_of_stomach	
distention_of_abdomen	
fluid_overload	
vomiting	
yellowish_skin	
abdominal_pain	
swelling_of_stomach	
distention_of_abdomen	
history_of_alcohol_consumption	
fluid_overload	
vomiting	
yellowish_skin	
abdominal_pain	
swelling_of_stomach	
distention_of_abdomen	
history_of_alcohol_consumption	
vomiting	
yellowish_skin	
swelling_of_stomach	
distention_of_abdomen	
history_of_alcohol_consumption	
fluid_overload	
yellowish_skin	
abdominal_pain	
swelling_of_stomach	
distention_of_abdomen	
history_of_alcohol_consumption	
fluid_overload	
continuous_sneezing	
chills	
watering_from_eyes	
continuous_sneezing	
shivering	
chills	
watering_from_eyes	
continuous_sneezing	
shivering	
chills	
continuous_sneezing	
shivering	
watering_from_eyes	
shivering	
chills	
watering_from_eyes	
muscle_weakness	
stiff_neck	
movement_stiffness	
painful_walking	
muscle_weakness	
stiff_neck	
swelling_joints	
movement_stiffness	
painful_walking	
muscle_weakness	
stiff_neck	
swelling_joints	
movement_stiffness	
muscle_weakness	
stiff_neck	
swelling_joints	
painful_walking	
muscle_weakness	
swelling_joints	
movement_stiffness	
painful_walking	
stiff_neck	
swelling_joints	
movement_stiffness	
painful_walking	
cough	
high_fever	
breathlessness	
family_history	
mucoid_sputum	
fatigue	
cough	
breathlessness	
family_history	
mucoid_sputum	
fatigue	
cough	
high_fever	
breathlessness	
family_history	
mucoid_sputum	
fatigue	
cough	
high_fever	
breathlessness	
family_history	
mucoid_sputum	
fatigue	
cough	
high_fever	
breathlessness	
mucoid_sputum	
fatigue	
cough	
high_fever	
family_history	
mucoid_sputum	
fatigue	
cough	
high_fever	
breathlessness	
family_history	
fatigue	
cough	
high_fever	
breathlessness	
mucoid_sputum	
back_pain	
neck_pain	
dizziness	
loss_of_balance	
back_pain	
weakness_in_limbs	
dizziness	
loss_of_balance	
back_pain	
weakness_in_limbs	
neck_pain	
dizziness	
loss_of_balance	
back_pain	
weakness_in_limbs	
neck_pain	
dizziness	
back_pain	
weakness_in_limbs	
neck_pain	
loss_of_balance	
back_pain	
weakness_in_limbs	
neck_pain	
loss_of_balance	
weakness_in_limbs	
neck_pain	
dizziness	
loss_of_balance	
skin_rash	
fatigue	
lethargy	
high_fever	
headache	
loss_of_appetite	
mild_fever	
swelled_lymph_nodes	
malaise	
red_spots_over_body	
itching	
fatigue	
lethargy	
high_fever	
headache	
loss_of_appetite	
mild_fever	
swelled_lymph_nodes	
malaise	
red_spots_over_body	
itching	
skin_rash	
fatigue	
high_fever	
headache	
loss_of_appetite	
mild_fever	
swelled_lymph_nodes	
malaise	
red_spots_over_body	
itching	
skin_rash	
fatigue	
lethargy	
headache	
loss_of_appetite	
mild_fever	
swelled_lymph_nodes	
malaise	
red_spots_over_body	
itching	
skin_rash	
fatigue	
lethargy	
high_fever	
headache	
loss_of_appetite	
mild_fever	
malaise	
red_spots_over_body	
itching	
skin_rash	
fatigue	
lethargy	
high_fever	
headache	
loss_of_appetite	
mild_fever	
swelled_lymph_nodes	
malaise	
red_spots_over_body	
itching	
skin_rash	
fatigue	
lethargy	
high_fever	
headache	
loss_of_appetite	
mild_fever	
swelled_lymph_nodes	
malaise	
red_spots_over_body	
itching	
skin_rash	
fatigue	
lethargy	
high_fever	
headache	
loss_of_appetite	
mild_fever	
malaise	
red_spots_over_body	
itching	
skin_rash	
fatigue	
lethargy	
high_fever	
loss_of_appetite	
mild_fever	
swelled_lymph_nodes	
malaise	
red_spots_over_body	
itching	
skin_rash	
fatigue	
lethargy	
high_fever	
headache	
loss_of_appetite	
mild_fever	
swelled_lymph_nodes	
malaise	
red_spots_over_body	
itching	
skin_rash	
fatigue	
lethargy	
high_fever	
headache	
loss_of_appetite	
mild_fever	
swelled_lymph_nodes	
malaise	
red_spots_over_body	
itching	
skin_rash	
fatigue	
lethargy	
high_fever	
loss_of_appetite	
mild_fever	
swelled_lymph_nodes	
malaise	
red_spots_over_body	
itching	
skin_rash	
fatigue	
lethargy	
high_fever	
headache	
loss_of_appetite	
mild_fever	
swelled_lymph_nodes	
malaise	
red_spots_over_body	
itching	
skin_rash	
fatigue	
lethargy	
high_fever	
headache	
loss_of_appetite	
mild_fever	
swelled_lymph_nodes	
malaise	
red_spots_over_body	
itching	
skin_rash	
fatigue	
lethargy	
high_fever	
headache	
loss_of_appetite	
mild_fever	
swelled_lymph_nodes	
malaise	
red_spots_over_body	
itching	
skin_rash	
fatigue	
lethargy	
high_fever	
headache	
loss_of_appetite	
mild_fever	
swelled_lymph_nodes	
malaise	
red_spots_over_body	
itching	
skin_rash	
fatigue	
lethargy	
high_fever	
headache	
loss_of_appetite	
mild_fever	
swelled_lymph_nodes	
malaise	
red_spots_over_body	
itching	
skin_rash	
fatigue	
lethargy	
high_fever	
headache	
loss_of_appetite	
mild_fever	
swelled_lymph_nodes	
malaise	
red_spots_over_body	
itching	
skin_rash	
fatigue	
lethargy	
high_fever	
headache	
loss_of_appetite	
mild_fever	
swelled_lymph_nodes	
malaise	
red_spots_over_body	
itching	
skin_rash	
fatigue	
lethargy	
high_fever	
headache	
loss_of_appetite	
mild_fever	
swelled_lymph_nodes	
malaise	
red_spots_over_body	
itching	
skin_rash	
fatigue	
lethargy	
high_fever	
headache	
loss_of_appetite	
mild_fever	
swelled_lymph_nodes	
malaise	
red_spots_over_body	
itching	
skin_rash	
fatigue	
lethargy	
high_fever	
headache	
loss_of_appetite	
mild_fever	
swelled_lymph_nodes	
malaise	
red_spots_over_body	
itching	
skin_rash	
fatigue	
lethargy	
high_fever	
headache	
loss_of_appetite	
mild_fever	
swelled_lymph_nodes	
malaise	
red_spots_over_body	
itching	
skin_rash	
fatigue	
lethargy	
high_fever	
headache	
loss_of_appetite	
mild_fever	
swelled_lymph_nodes	
malaise	
red_spots_over_body	
itching	
skin_rash	
fatigue	
lethargy	
high_fever	
headache	
loss_of_appetite	
mild_fever	
swelled_lymph_nodes	
malaise	
red_spots_over_body	
itching	
skin_rash	
fatigue	
lethargy	
high_fever	
headache	
loss_of_appetite	
mild_fever	
swelled_lymph_nodes	
malaise	
red_spots_over_body	
itching	
skin_rash	
fatigue	
lethargy	
high_fever	
headache	
loss_of_appetite	
mild_fever	
swelled_lymph_nodes	
malaise	
red_spots_over_body	
itching	
skin_rash	
fatigue	
lethargy	
high_fever	
headache	
loss_of_appetite	
mild_fever	
swelled_lymph_nodes	
malaise	
red_spots_over_body	
itching	
skin_rash	
fatigue	
lethargy	
high_fever	
headache	
loss_of_appetite	
mild_fever	
swelled_lymph_nodes	
malaise	`;



export const medicalData = [
    { disease: "AIDS", symptoms: ["muscle_wasting", "high_fever", "extra_marital_contacts", "patches_in_throat"] },
    { disease: "Acne", symptoms: ["pus_filled_pimples", "blackheads", "scurring", "skin_rash", "high_fever"] },
    { disease: "Alcoholic hepatitis", symptoms: ["vomiting", "abdominal_pain", "swelling_of_stomach", "distention_of_abdomen", "history_of_alcohol_consumption", "fluid_overload", "yellowish_skin"] },
    { disease: "Allergy", symptoms: ["continuous_sneezing", "chills", "watering_from_eyes", "shivering"] },
    { disease: "Arthritis", symptoms: ["muscle_weakness", "stiff_neck", "movement_stiffness", "painful_walking", "swelling_joints"] },
    { disease: "Asthma", symptoms: ["cough", "high_fever", "breathlessness", "family_history", "mucoid_sputum", "fatigue"] },
    { disease: "Cervical spondylosis", symptoms: ["back_pain", "neck_pain", "dizziness", "loss_of_balance", "weakness_in_limbs"] },
    { disease: "Chicken pox", symptoms: ["skin_rash", "fatigue", "lethargy", "high_fever", "headache", "loss_of_appetite", "mild_fever", "swelled_lymph_nodes", "malaise", "red_spots_over_body", "itching"] },
    { disease: "Chronic cholestasis", symptoms: ["vomiting", "yellowish_skin", "nausea", "loss_of_appetite", "abdominal_pain", "yellowing_of_eyes", "itching"] },
    { disease: "Common Cold", symptoms: ["chills", "fatigue", "cough", "high_fever", "headache", "swelled_lymph_nodes", "malaise", "phlegm", "throat_irritation", "redness_of_eyes", "sinus_pressure", "runny_nose", "congestion", "continuous_sneezing"] },
    { disease: "Dengue", symptoms: ["chills", "joint_pain", "vomiting", "fatigue", "high_fever", "headache", "nausea", "loss_of_appetite", "pain_behind_the_eyes", "back_pain", "malaise", "muscle_pain", "red_spots_over_body", "skin_rash"] },
    { disease: "Diabetes", symptoms: ["fatigue", "restlessness", "lethargy", "irregular_sugar_level", "blurred_and_distorted_vision", "obesity", "excessive_hunger", "increased_appetite", "polyuria", "weight_loss"] },
    { disease: "Dimorphic hemmorhoids(piles)", symptoms: ["constipation", "pain_during_bowel_movements", "bloody_stool", "irritation_in_anus", "pain_in_anal_region"] },
    { disease: "Drug Reaction", symptoms: ["skin_rash", "stomach_pain", "burning_micturition", "spotting_urination", "itching"] },
    { disease: "Fungal infection", symptoms: ["skin_rash", "nodal_skin_eruptions", "dischromic_patches", "itching"] },
    { disease: "Ocular Fungal infection", symptoms: ["itching", "skin_rash", "nodal_skin_eruptions"] },
    { disease: "GERD", symptoms: ["acidity", "ulcers_on_tongue", "vomiting", "cough", "chest_pain", "stomach_pain"] },
    { disease: "Gastroenteritis", symptoms: ["sunken_eyes", "dehydration", "diarrhoea", "vomiting"] },
    { disease: "Heart attack", symptoms: ["breathlessness", "sweating", "chest_pain", "vomiting"] },
    { disease: "Hepatitis B", symptoms: ["fatigue", "lethargy", "yellowish_skin", "dark_urine", "loss_of_appetite", "abdominal_pain", "yellow_urine", "yellowing_of_eyes", "malaise", "receiving_blood_transfusion", "receiving_unsterile_injections", "itching"] },
    { disease: "Jaundice", symptoms: ["itching", "vomiting", "weight_loss", "high_fever", "yellowish_skin", "dark_urine", "abdominal_pain"] },
    { disease: "Malaria", symptoms: ["chills", "high_fever", "sweating", "headache", "nausea", "diarrhoea", "muscle_pain"] },
    { disease: "Migraine", symptoms: ["acidity", "headache", "blurred_and_distorted_vision", "excessive_hunger", "stiff_neck", "depression", "irritability", "visual_disturbances"] },
    { disease: "Osteoarthristis", symptoms: ["joint_pain", "knee_pain", "hip_joint_pain", "swelling_joints", "painful_walking"] },
    { disease: "Paralysis (brain hemorrhage)", symptoms: ["headache", "weakness_of_one_body_side", "altered_sensorium", "vomiting"] },
    { disease: "Peptic ulcer", symptoms: ["indigestion", "loss_of_appetite", "abdominal_pain", "passage_of_gases", "internal_itching"] },
    { disease: "Pneumonia", symptoms: ["chills", "fatigue", "cough", "high_fever", "breathlessness", "sweating", "malaise", "phlegm", "chest_pain", "fast_heart_rate", "rusty_sputum"] },
    { disease: "Psoriasis", symptoms: ["joint_pain", "skin_peeling", "silver_like_dusting", "small_dents_in_nails", "inflammatory_nails", "skin_rash"] },
    { disease: "Tuberculosis", symptoms: ["chills", "fatigue", "weight_loss", "cough", "high_fever", "breathlessness", "sweating", "loss_of_appetite", "mild_fever", "yellowing_of_eyes", "swelled_lymph_nodes", "malaise", "phlegm"] },
    { disease: "Typhoid", symptoms: ["chills", "fatigue", "high_fever", "headache", "nausea", "constipation", "abdominal_pain", "diarrhoea", "toxic_look_(typhos)", "belly_pain"] },
    { disease: "Urinary tract infection", symptoms: ["bladder_discomfort", "foul_smell_of urine", "continuous_feel_of_urine", "burning_micturition"] },
    { disease: "Varicose veins", symptoms: ["cramps", "bruising", "obesity", "swollen_legs", "swollen_blood_vessels", "prominent_veins_on_calf", "fatigue"] },
    { disease: "Hepatitis A", symptoms: ["joint_pain", "vomiting", "dark_urine", "nausea", "loss_of_appetite", "abdominal_pain", "diarrhoea", "mild_fever", "yellowing_of_eyes", "muscle_pain", "yellowish_skin"] },
    { disease: "Vertigo", symptoms: ["headache", "nausea", "spinning_movements", "loss_of_balance", "unsteadiness", "vomiting"] }
];
